<h2 align='center'>Image Classification Using Convolutional Neural Network (CNN)</h2>

In [44]:
import tensorflow as tf
from tensorflow.keras import datasets, layers, models
import matplotlib.pyplot as plt
import numpy as np

<h4>Loading the dataset</h4>

In [68]:
(X_train, y_train), (X_test,y_test) = datasets.cifar10.load_data()

In [69]:
y_train = y_train.reshape(-1,)
y_train[:5]

array([6, 9, 9, 4, 1], dtype=uint8)

In [72]:
y_test = y_test.reshape(-1,)
y_train[:5]

array([6, 9, 9, 4, 1], dtype=uint8)

In [71]:
classes = ["airplane","automobile","bird","cat","deer","dog","frog","horse","ship","truck"]

<h4>Normalizing the training data</h4>

In [12]:
X_train = X_train / 255.0
X_test = X_test / 255.0

<h4>Building a convolutional neural network to train the images</h4>

In [45]:
cnn = models.Sequential([
    layers.Conv2D(filters=32, kernel_size=(3, 3), activation='relu', input_shape=(32, 32, 3)),
    layers.MaxPooling2D((2, 2)),
    
    layers.Conv2D(filters=64, kernel_size=(3, 3), activation='relu'),
    layers.MaxPooling2D((2, 2)),
    
    layers.Flatten(),
    layers.Dense(64, activation='relu'),
    layers.Dense(10, activation='softmax')
])

In [46]:
cnn.compile(optimizer='sgd',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [48]:
cnn.fit(X_train, y_train, epochs=100)

Epoch 1/100
1563/1563 [==============================] - 17s 11ms/step - loss: 1.8436 - accuracy: 0.3377
Epoch 2/100
1563/1563 [==============================] - 17s 11ms/step - loss: 1.5530 - accuracy: 0.4474
Epoch 3/100
1563/1563 [==============================] - 16s 10ms/step - loss: 1.3966 - accuracy: 0.5033
Epoch 4/100
1563/1563 [==============================] - 16s 11ms/step - loss: 1.3086 - accuracy: 0.5374
Epoch 5/100
1563/1563 [==============================] - 17s 11ms/step - loss: 1.2371 - accuracy: 0.5629
Epoch 6/100
1563/1563 [==============================] - 17s 11ms/step - loss: 1.1757 - accuracy: 0.5887
Epoch 7/100
1563/1563 [==============================] - 17s 11ms/step - loss: 1.1175 - accuracy: 0.6076
Epoch 8/100
1563/1563 [==============================] - 17s 11ms/step - loss: 1.0708 - accuracy: 0.6284
Epoch 9/100
1563/1563 [==============================] - 17s 11ms/step - loss: 1.0259 - accuracy: 0.6437
Epoch 10/100
1563/1563 [==============================]

1563/1563 [==============================] - 14s 9ms/step - loss: 0.0039 - accuracy: 1.0000
Epoch 79/100
1563/1563 [==============================] - 15s 10ms/step - loss: 0.0037 - accuracy: 1.0000
Epoch 80/100
1563/1563 [==============================] - 14s 9ms/step - loss: 0.0035 - accuracy: 1.0000
Epoch 81/100
1563/1563 [==============================] - 15s 10ms/step - loss: 0.0034 - accuracy: 1.0000
Epoch 82/100
1563/1563 [==============================] - 14s 9ms/step - loss: 0.0032 - accuracy: 1.0000
Epoch 83/100
1563/1563 [==============================] - 14s 9ms/step - loss: 0.0031 - accuracy: 1.0000
Epoch 84/100
1563/1563 [==============================] - 14s 9ms/step - loss: 0.0030 - accuracy: 1.0000
Epoch 85/100
1563/1563 [==============================] - 14s 9ms/step - loss: 0.0029 - accuracy: 1.0000
Epoch 86/100
1563/1563 [==============================] - 14s 9ms/step - loss: 0.0027 - accuracy: 1.0000
Epoch 87/100
1563/1563 [==============================] - 14s 9ms/

In [65]:
cnn.evaluate(X_test,y_test)

313/313 [==============================] - 4s 4ms/step - loss: 2.9912 - accuracy: 0.6815


[2.9912309646606445, 0.6815000176429749]

In [66]:
y_pred = cnn.predict(X_test)

313/313 [==============================] - 4s 4ms/step


In [67]:
y_classes = [np.argmax(element) for element in y_pred]
y_classes[:5]

[3, 8, 1, 0, 4]

In [64]:
y_test[:5]

array([3, 8, 8, 0, 6], dtype=uint8)